COM207- Appointment Creation From
Grovy/ChameleonBusinessStudio pull request #47
Opened 2022-10-07 19:25 UTC by Rojanmhj2055

Updated styling of appointment Creation form and added Page Not Found page.

2022-10-07 20:39 UTC, rramsdany commented on angular-app/src/app/pages/admin-panel/admin-panel/admin-panel.component.css
> -mat-tab-group{
Why are you deleting all this?

2022-10-07 20:41 UTC, rramsdany commented on angular-app/src/app/pages/admin-panel/admin-panel/admin-panel.component.html
> +<!-- Author:Ariel Camargo-->
This is introducing an old version of Admin Panel, you need to pull changes from main first before merging this PR

2022-10-07 20:42 UTC, rramsdany requested changes
I think you may have not pulled changes from main before starting this PR. Please pull from `origin main` before PR this because you're trying to push an old version of the `admin-panel` component. I see this branch is 13 commits behind so pulling will fix this.
 
Correct me if I'm wrong but I don't believe you did any new work for this component?

2022-10-07 20:43 UTC, rramsdany commented on angular-app/src/app/page-not-found/page-not-found.component.html
> +    <p class="business-title">Chameleon <Br>Business Studio</p>
Awesome page, we needed something like this!

2022-10-07 20:43 UTC, rramsdany commented on angular-app/src/app/app-routing.module.ts
> +import { AppointmentCreateFormComponent } from './pages/appointments/appointment-create-form/appointment-create-form.component';
Please keep the imports in this file in alphabetical order

2022-10-07 22:03 UTC, Matt-Crow commented on angular-app/src/app/app.module.ts
> +      {path:'**',component:PageNotFoundComponent}
Great idea, I like it!

2022-10-07 22:07 UTC, Matt-Crow approved these changes
Everything looks good to me except for the stuff @rramsdany pointed out. I'll approve it, but those changes he suggests should still be made

2022-10-10 20:20 UTC, rramsdany commented
@Rojanmhj2055 You still need to correct the files from your first commit because this PR is aiming to revert the admin panel to a previous version

2022-10-11 01:52 UTC, rramsdany commented on angular-app/src/app/app.module.ts
> +<<<<<<< HEAD
You have to delete these boiler plate git code throughout these files.

2022-10-11 01:52 UTC, rramsdany commented on angular-app/src/app/app.module.ts
> +>>>>>>> parent of 637e1a1 (COM207- Appointment Creation From)
Here

2022-10-11 01:53 UTC, rramsdany commented on angular-app/src/app/pages/appointments/appointment-create-form/appointment-create-form.component.css
> +>>>>>>> parent of 637e1a1 (COM207- Appointment Creation From)
Here too

2022-10-11 01:53 UTC, rramsdany commented on angular-app/src/app/pages/appointments/appointment-create-form/appointment-create-form.component.html
> +<<<<<<< HEAD
Here

2022-10-11 01:53 UTC, rramsdany commented on angular-app/src/app/pages/appointments/appointment-create-form/appointment-create-form.component.ts
> +=======
This file too

2022-10-11 04:29 UTC, rramsdany approved these changes

2022-10-11 04:40 UTC, merged