COM-218 Create /getAppointments Endpoint
Grovy/ChameleonBusinessStudio pull request #61
Opened 2022-10-20 02:01 UTC by dkaercher

Adds /getAppointments endpoint to return all appointments from the Vendia database.

![image](https://user-images.githubusercontent.com/91099552/196838209-a082d879-5829-4021-9724-3a2714863d16.png)

![image](https://user-images.githubusercontent.com/91099552/196838283-98fc7f8e-f85b-4a0d-9f2d-f54dae4d0f8f.png)

2022-10-20 02:10 UTC, dvillavicencio requested changes

2022-10-20 02:10 UTC, dvillavicencio commented on src/main/java/com/compilercharisma/chameleonbusinessstudio/controller/AppointmentControllerv2.java
I wanna approve but we should start writing unit tests for these simple classes like the `Repository.java` classes and the `Service.java` classes, there are various examples under `/src/main/tests/`

Here Dave, you can unit test:
In `AppointmentRepositoryv2.java` you can test the function `findallAppointments()`
In `AppointmentServicev2.java` you can test the function `getAllAppointments()`

2022-10-22 19:37 UTC, arielcamargo approved these changes

2022-10-24 04:18 UTC, dvillavicencio requested changes

2022-10-24 04:18 UTC, dvillavicencio commented on src/main/java/com/compilercharisma/chameleonbusinessstudio/repository/AppointmentRepositoryv2.java
> +                }""";
You need to also make a test for this method.

2022-10-25 04:04 UTC, dvillavicencio approved these changes

2022-10-25 04:04 UTC, merged