More api endpoints
Grovy/ChameleonBusinessStudio pull request #66
Opened 2022-10-26 19:33 UTC by Matt-Crow

Added the following API endpoints, as well as tons of unit tests:

- `POST /api/v1/appointments/cancel/{appt-id}`
- `POST /api/v1/appointments/unbook-me/{appt-id}`
- `POST /api/v1/appointments/unbook-them/{appt-id}?email={email}`

2022-10-26 19:38 UTC, dkaercher approved these changes

2022-10-26 21:49 UTC, rramsdany approved these changes

2022-10-27 00:03 UTC, dvillavicencio requested changes

2022-10-27 00:03 UTC, dvillavicencio commented on src/main/java/com/compilercharisma/chameleonbusinessstudio/exception/NoUserLoggedInHandler.java
> +package com.compilercharisma.chameleonbusinessstudio.exception;
I think its appropiate this class should be moved to the `controller` package because it returns HTTP statuses in case of errors, very minor though.

2022-10-27 00:03 UTC, dvillavicencio commented on src/main/java/com/compilercharisma/chameleonbusinessstudio/repository/AppointmentRepositoryv2.java
> +                	}
For queries and simplicity, we should put them all in one line, i found that for integration tests this is very beneficial

2022-10-27 00:03 UTC, dvillavicencio commented on src/main/java/com/compilercharisma/chameleonbusinessstudio/repository/AppointmentRepositoryv2.java
> +                		}
Same here

2022-10-28 00:39 UTC, dvillavicencio approved these changes
Looks good to me.

2022-10-28 00:45 UTC, merged